services:
  mattermost-app-nextcloud:
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - STATIC_FOLDER=${STATIC_FOLDER:-static}
      - APP_TYPE=${APP_TYPE:-HTTP}
      - CHUNK_FILE_SIZE_MB=${CHUNK_FILE_SIZE_MB:-15}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-25}
      - MAX_FILES_SIZE_MB=${MAX_FILES_SIZE_MB:-50}
      - APP_URL=${APP_URL:-http://localhost:8082}
      - PORT=${PORT:-8082}
      - MAX_REQUEST_RETRIES=${MAX_REQUEST_RETRIES:-3}

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-8082}:${PORT:-8082}'